export const CHANGE_NAV = 'CHANGE_NAV';
export const SEARCH_INPUT_VAL = "SEARCH_INPUT_VAL";
export const MESSAGE_CHECKED = "MESSAGE_CHECKED";
export const NOTI_CHECKED = "NOTI_CHECKED";
export const NOTI_DATA = "NOTI_DATA";
export const MESSAGE_DATA = "MESSAGE_DATA";