name: Next.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Build CRA App
      run: |
        npm install
        npm run build
